export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';

export const REMOVE_PRODUCT_ERROR = 'REMOVE_PRODUCT_ERROR';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';

export const UNDELETE_PRODUCT_ERROR = 'UNDELETE_PRODUCT_ERROR';

export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';

export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const UNLOAD_PRODUCTS_SUCCESS = 'UNLOAD_PRODUCTS_SUCCESS';
