export const CREATE_API_ERROR = 'CREATE_API_ERROR';
export const CREATE_API_SUCCESS = 'CREATE_API_SUCCESS';

export const REMOVE_API_ERROR = 'REMOVE_API_ERROR';
export const REMOVE_API_SUCCESS = 'REMOVE_API_SUCCESS';

export const UNDELETE_API_ERROR = 'UNDELETE_API_ERROR';

export const UPDATE_API_ERROR = 'UPDATE_API_ERROR';
export const UPDATE_API_SUCCESS = 'UPDATE_API_SUCCESS';

export const FILTER_APIS = 'FILTER_APIS';
export const LOAD_APIS_SUCCESS = 'LOAD_APIS_SUCCESS';
export const UNLOAD_APIS_SUCCESS = 'UNLOAD_APIS_SUCCESS';
